ALTER TABLE players ADD COLUMN public_profile_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN ranked_points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN duels_played INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN wins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN losses INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN draws INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN profile_updated_utc INTEGER NOT NULL DEFAULT 0;
