using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace ArcaneArena.Frontend
{
    public enum PackOrigin : byte
    {
        Manual = 0,
        AutoGenerated = 1
    }

    public static class OnlineDuelCoinReward
    {
        public const int MaximumDamage = 8000;
        public const int DamagePerCoin = 150;

        public static int Calculate(
            int damageDealt,
            int completedRounds,
            bool winner,
            bool draw = false)
        {
            if (draw)
                return 0;

            int cappedDamage = Math.Max(0, Math.Min(MaximumDamage, damageDealt));
            int baseCoins = cappedDamage / DamagePerCoin;
            if (!winner)
                return baseCoins / 2;

            int penalty = completedRounds >= 9
                ? 12
                : completedRounds == 8
                    ? 8
                    : completedRounds == 7
                        ? 4
                        : 0;
            return Math.Max(0, baseCoins - penalty);
        }
    }

    public static class OfflineDuelCoinReward
    {
        public const int MinimumCoins = 10;
        public const int MaximumCoins = 50;

        public static int Calculate(
            long damageDealt,
            long damageReceived,
            int turns,
            int confirmedPlays,
            bool winner,
            bool draw)
        {
            int resultBase = winner ? 20 : draw ? 14 : MinimumCoins;
            int offense = Mathf.FloorToInt(
                Mathf.Clamp01(damageDealt / 8000f) * 18f);
            int survival = Mathf.FloorToInt(
                (1f - Mathf.Clamp01(damageReceived / 8000f)) * 7f);
            int activity = Mathf.FloorToInt(
                Mathf.Clamp01(confirmedPlays / 8f) * 5f);
            int pacePenalty = Math.Max(0, Math.Max(0, turns) - 12) / 3;
            return Math.Max(
                MinimumCoins,
                Math.Min(
                    MaximumCoins,
                    resultBase + offense + survival + activity - pacePenalty));
        }
    }

    public sealed class ShopPackDefinition
    {
        public string PackId { get; }
        public string DisplayName { get; }
        public string Description { get; }
        public IReadOnlyList<string> CardIds { get; }
        public IReadOnlyList<string> PreviewCardIds { get; }
        public int PriceCoins { get; }
        public PackOrigin Origin { get; }
        public string GenerationBatchId { get; }
        public int GeneratorVersion { get; }
        public bool ContentLockedAfterPublish { get; }
        public string ContentHash { get; }
        public bool CountsForAutoCoverage { get; }
        public bool ManualVisualOverride { get; }
        public bool NeedsPreviewReview { get; }
        public string CoverCardId => CardIds.Count > 0
            ? CardIds[0]
            : string.Empty;

        public ShopPackDefinition(
            string packId,
            string displayName,
            string description,
            IEnumerable<string> cardIds,
            IEnumerable<string> previewCardIds = null,
            int priceCoins = 25,
            PackOrigin origin = PackOrigin.Manual,
            string generationBatchId = "",
            int generatorVersion = 0,
            bool contentLockedAfterPublish = true,
            string contentHash = "",
            bool countsForAutoCoverage = true,
            bool manualVisualOverride = false,
            bool needsPreviewReview = false)
        {
            PackId = packId ?? string.Empty;
            DisplayName = displayName ?? string.Empty;
            Description = description ?? string.Empty;
            CardIds = (cardIds ?? Array.Empty<string>())
                .Select(FrontendCardIdentity.NormalizeOfficialId)
                .Where(id => !string.IsNullOrWhiteSpace(id))
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            string[] normalizedPreviews = (previewCardIds ?? Array.Empty<string>())
                .Select(FrontendCardIdentity.NormalizeOfficialId)
                .Where(id => CardIds.Contains(id, StringComparer.Ordinal))
                .Distinct(StringComparer.Ordinal)
                .Take(3)
                .ToArray();
            if (normalizedPreviews.Length < 3 && CardIds.Count > 0)
            {
                normalizedPreviews = new[]
                    {
                        CardIds[0],
                        CardIds[CardIds.Count / 2],
                        CardIds[CardIds.Count - 1]
                    }
                    .Distinct(StringComparer.Ordinal)
                    .Concat(CardIds)
                    .Distinct(StringComparer.Ordinal)
                    .Take(Math.Min(3, CardIds.Count))
                    .ToArray();
            }
            PreviewCardIds = normalizedPreviews;
            PriceCoins = priceCoins > 0 ? priceCoins : 25;
            Origin = origin;
            GenerationBatchId = generationBatchId ?? string.Empty;
            GeneratorVersion = Math.Max(0, generatorVersion);
            ContentLockedAfterPublish = contentLockedAfterPublish;
            ContentHash = contentHash ?? string.Empty;
            CountsForAutoCoverage = countsForAutoCoverage;
            ManualVisualOverride = manualVisualOverride;
            NeedsPreviewReview = needsPreviewReview;
        }
    }

    /// <summary>
    /// Catálogo imutável e versionado. Todas as cartas colecionáveis aparecem
    /// exatamente uma vez e os pools são mantidos em tamanho comercial.
    /// </summary>
    public static class ShopPackCatalog
    {
        public const int CatalogVersion = 2;
        public const int CatalogSeed = 23082026;
        public const int PackPriceCoins = 25;
        public const int CardsPerOpening = 5;
        public const int MinimumCardsPerPack = 40;
        public const int MaximumCardsPerPack = 85;
        public const int PreferredCardsPerPack = 82;

        private static readonly IReadOnlyList<ShopPackDefinition> Definitions =
            LoadDefinitions();

        public static IReadOnlyList<ShopPackDefinition> Packs => Definitions;

        public static ShopPackDefinition Find(string packId)
        {
            return Definitions.FirstOrDefault(pack => string.Equals(
                pack.PackId,
                packId,
                StringComparison.Ordinal));
        }

        private static IReadOnlyList<ShopPackDefinition> LoadDefinitions()
        {
            TextAsset asset = Resources.Load<TextAsset>("Shop/PackCatalog");
            if (asset == null)
            {
                Debug.LogError(
                    "Catálogo versionado ausente em Resources/Shop/PackCatalog.json.");
                return Array.Empty<ShopPackDefinition>();
            }

            ShopPackCatalogFile file =
                JsonUtility.FromJson<ShopPackCatalogFile>(asset.text);
            if (file == null || file.version != CatalogVersion ||
                file.seed != CatalogSeed || file.packs == null)
            {
                Debug.LogError("Catálogo de pacotes incompatível ou inválido.");
                return Array.Empty<ShopPackDefinition>();
            }

            return file.packs
                .Where(pack => pack != null)
                .Select(pack => new ShopPackDefinition(
                    pack.packId,
                    pack.displayName,
                    pack.description,
                    pack.cardIds,
                    pack.previewCardIds,
                    pack.priceCoins,
                    (PackOrigin)Mathf.Clamp(pack.origin, 0, 1),
                    pack.generationBatchId,
                    pack.generatorVersion,
                    pack.contentLockedAfterPublish || pack.origin == 0,
                    pack.contentHash,
                    pack.countsForAutoCoverage || pack.origin == 0,
                    pack.manualVisualOverride,
                    pack.needsPreviewReview))
                .ToArray();
        }
    }

    [Serializable]
    internal sealed class ShopPackCatalogFile
    {
        public int version;
        public int seed;
        public ShopPackCatalogRecord[] packs;
    }

    [Serializable]
    internal sealed class ShopPackCatalogRecord
    {
        public string packId;
        public string displayName;
        public string description;
        public string[] cardIds;
        public string[] previewCardIds;
        public int priceCoins;
        public int origin;
        public string generationBatchId;
        public int generatorVersion;
        public bool contentLockedAfterPublish;
        public string contentHash;
        public bool countsForAutoCoverage;
        public bool manualVisualOverride;
        public bool needsPreviewReview;
    }
}
