using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace ArcaneArena.Frontend
{
    public enum PackOrigin : byte
    {
        Manual = 0,
        AutoGenerated = 1
    }

    public static class OnlineDuelCoinReward
    {
        public const int MaximumDamage = 8000;
        public const int DamagePerCoin = 150;

        public static int Calculate(
            int damageDealt,
            int completedRounds,
            bool winner,
            bool draw = false)
        {
            if (draw)
                return 0;

            int cappedDamage = Math.Max(0, Math.Min(MaximumDamage, damageDealt));
            int baseCoins = cappedDamage / DamagePerCoin;
            if (!winner)
                return baseCoins / 2;

            int penalty = completedRounds >= 9
                ? 12
                : completedRounds == 8
                    ? 8
                    : completedRounds == 7
                        ? 4
                        : 0;
            return Math.Max(0, baseCoins - penalty);
        }
    }

    public sealed class ShopPackDefinition
    {
        public string PackId { get; }
        public string DisplayName { get; }
        public string Description { get; }
        public IReadOnlyList<string> CardIds { get; }
        public IReadOnlyList<string> PreviewCardIds { get; }
        public int PriceCoins { get; }
        public PackOrigin Origin { get; }
        public string GenerationBatchId { get; }
        public int GeneratorVersion { get; }
        public bool ContentLockedAfterPublish { get; }
        public string ContentHash { get; }
        public bool CountsForAutoCoverage { get; }
        public bool ManualVisualOverride { get; }
        public bool NeedsPreviewReview { get; }
        public string CoverCardId => CardIds.Count > 0
            ? CardIds[0]
            : string.Empty;

        public ShopPackDefinition(
            string packId,
            string displayName,
            string description,
            IEnumerable<string> cardIds,
            IEnumerable<string> previewCardIds = null,
            int priceCoins = 35,
            PackOrigin origin = PackOrigin.Manual,
            string generationBatchId = "",
            int generatorVersion = 0,
            bool contentLockedAfterPublish = true,
            string contentHash = "",
            bool countsForAutoCoverage = true,
            bool manualVisualOverride = false,
            bool needsPreviewReview = false)
        {
            PackId = packId ?? string.Empty;
            DisplayName = displayName ?? string.Empty;
            Description = description ?? string.Empty;
            CardIds = (cardIds ?? Array.Empty<string>())
                .Select(FrontendCardIdentity.NormalizeOfficialId)
                .Where(id => !string.IsNullOrWhiteSpace(id))
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            string[] normalizedPreviews = (previewCardIds ?? Array.Empty<string>())
                .Select(FrontendCardIdentity.NormalizeOfficialId)
                .Where(id => CardIds.Contains(id, StringComparer.Ordinal))
                .Distinct(StringComparer.Ordinal)
                .Take(3)
                .ToArray();
            if (normalizedPreviews.Length < 3 && CardIds.Count > 0)
            {
                normalizedPreviews = new[]
                    {
                        CardIds[0],
                        CardIds[CardIds.Count / 2],
                        CardIds[CardIds.Count - 1]
                    }
                    .Distinct(StringComparer.Ordinal)
                    .Concat(CardIds)
                    .Distinct(StringComparer.Ordinal)
                    .Take(Math.Min(3, CardIds.Count))
                    .ToArray();
            }
            PreviewCardIds = normalizedPreviews;
            PriceCoins = priceCoins > 0 ? priceCoins : 35;
            Origin = origin;
            GenerationBatchId = generationBatchId ?? string.Empty;
            GeneratorVersion = Math.Max(0, generatorVersion);
            ContentLockedAfterPublish = contentLockedAfterPublish;
            ContentHash = contentHash ?? string.Empty;
            CountsForAutoCoverage = countsForAutoCoverage;
            ManualVisualOverride = manualVisualOverride;
            NeedsPreviewReview = needsPreviewReview;
        }
    }

    /// <summary>
    /// Catálogo imutável e versionado. A distribuição das 106 cartas reais
    /// não é regenerada ao iniciar o jogo e cada ID aparece uma única vez.
    /// </summary>
    public static class ShopPackCatalog
    {
        public const int CatalogVersion = 1;
        public const int CatalogSeed = 12062026;
        public const int PackPriceCoins = 35;
        public const int CardsPerOpening = 5;

        private static readonly IReadOnlyList<ShopPackDefinition> LegacyExamples =
            new[]
            {
                new ShopPackDefinition(
                    "pack-nexo-arcano-v1",
                    "Pacote Nexo Arcano",
                    "Monstros e suportes para abrir novas linhas de jogada.",
                    new[]
                    {
                        "02129638","02314238","02857636","03078380","04335645","05318639","07084129","07198399","07922915","08240199","09287078","10045474","10515412","11443677","12266229","13756293","14315573","14558127","15960641","16699558","17725109","17947697","19613556","20747792","23020408","24382602","24508238","26202165","30576089","30603688","33698022","34318086","34755994","36262024","38033121","38120068"
                    }),
                new ShopPackDefinition(
                    "pack-lendas-do-duelo-v1",
                    "Pacote Lendas do Duelo",
                    "Cartas clássicas, respostas e peças de Deck Adicional.",
                    new[]
                    {
                        "38342335","38517737","39030163","40908371","41721210","43219114","43321985","43892408","44095762","45986603","46411259","46986414","47222536","47963370","48680970","50237654","51632798","52684508","54332792","54693926","55144522","56120475","56132807","56532353","56920308","59438930","59514116","59822133","60948488","62089826","63391643","63519819","65741786","66961194","68462976"
                    }),
                new ShopPackDefinition(
                    "pack-eclipse-cibernetico-v1",
                    "Pacote Eclipse Cibernético",
                    "Ameaças modernas e ferramentas para completar sua coleção.",
                    new[]
                    {
                        "69015963","70828912","71039903","71044499","71143015","71413901","72989439","73628505","74677422","75190122","77754944","79571449","80088625","80326401","82732705","83011278","83555666","83764719","84013237","85442146","86331741","88177324","88240808","89604813","89631139","93437091","94259633","95477924","96471335","96561011","96729612","97077563","97268402","97631303","98502113"
                    })
            };

        private static readonly IReadOnlyList<ShopPackDefinition> Definitions =
            LoadDefinitions();

        public static IReadOnlyList<ShopPackDefinition> Packs => Definitions;

        public static ShopPackDefinition Find(string packId)
        {
            return Definitions.FirstOrDefault(pack => string.Equals(
                pack.PackId,
                packId,
                StringComparison.Ordinal));
        }

        private static IReadOnlyList<ShopPackDefinition> LoadDefinitions()
        {
            TextAsset asset = Resources.Load<TextAsset>("Shop/PackCatalog");
            if (asset == null)
            {
                Debug.LogError(
                    "Catálogo versionado ausente em Resources/Shop/PackCatalog.json.");
                return Array.Empty<ShopPackDefinition>();
            }

            ShopPackCatalogFile file =
                JsonUtility.FromJson<ShopPackCatalogFile>(asset.text);
            if (file == null || file.version != CatalogVersion ||
                file.seed != CatalogSeed || file.packs == null)
            {
                Debug.LogError("Catálogo de pacotes incompatível ou inválido.");
                return Array.Empty<ShopPackDefinition>();
            }

            return file.packs
                .Where(pack => pack != null)
                .Select(pack => new ShopPackDefinition(
                    pack.packId,
                    pack.displayName,
                    pack.description,
                    pack.cardIds,
                    pack.previewCardIds,
                    pack.priceCoins,
                    (PackOrigin)Mathf.Clamp(pack.origin, 0, 1),
                    pack.generationBatchId,
                    pack.generatorVersion,
                    pack.contentLockedAfterPublish || pack.origin == 0,
                    pack.contentHash,
                    pack.countsForAutoCoverage || pack.origin == 0,
                    pack.manualVisualOverride,
                    pack.needsPreviewReview))
                .ToArray();
        }
    }

    [Serializable]
    internal sealed class ShopPackCatalogFile
    {
        public int version;
        public int seed;
        public ShopPackCatalogRecord[] packs;
    }

    [Serializable]
    internal sealed class ShopPackCatalogRecord
    {
        public string packId;
        public string displayName;
        public string description;
        public string[] cardIds;
        public string[] previewCardIds;
        public int priceCoins;
        public int origin;
        public string generationBatchId;
        public int generatorVersion;
        public bool contentLockedAfterPublish;
        public string contentHash;
        public bool countsForAutoCoverage;
        public bool manualVisualOverride;
        public bool needsPreviewReview;
    }
}
