using System;
using System.Collections.Generic;

namespace ArcaneArena.Editor.AutoPacks
{
    internal static class AutoPackPaths
    {
        public const string Settings =
            "Assets/GameData/Shop/AutoPackGenerationSettings.asset";
        public const string Manifest =
            "Assets/GameData/Shop/AutoPackGenerationManifest.asset";
        public const string GeneratedFolder =
            "Assets/GameData/Shop/Packs/AutoGenerated";
        public const string Catalog =
            "Assets/Resources/Shop/PackCatalog.json";
        public const string CardCatalog =
            "Assets/Cards/CardCatalog.asset";
        public const string Report =
            "Docs/Generated/AutoPackGenerationReport.md";
        public const string DefaultPackSprite =
            "Assets/Templates/DeckEditor/downcard.png";
    }

    [Serializable]
    public sealed class GeneratedPackRecord
    {
        public string packId = string.Empty;
        public string assetGuid = string.Empty;
        public string generationBatchId = string.Empty;
        public string contentHash = string.Empty;
        public List<string> cardIds = new();
        public bool published;
        public bool manualVisualOverride;
    }

    internal sealed class CardCatalogSnapshot
    {
        public string Hash { get; set; } = string.Empty;
        public List<string> KnownCardIds { get; } = new();
        public List<string> CollectibleCardIds { get; } = new();
        public List<string> EligibleCardIds { get; } = new();
        public List<string> DeferredCardIds { get; } = new();
        public List<string> Warnings { get; } = new();
        public List<string> Errors { get; } = new();
    }

    internal sealed class AutoPackGenerationReport
    {
        public string PreviousHash { get; set; } = string.Empty;
        public string SourceHash { get; set; } = string.Empty;
        public List<string> NewCardIds { get; } = new();
        public List<string> RemovedPendingCardIds { get; } = new();
        public List<GeneratedPackRecord> CreatedPacks { get; } = new();
        public List<string> PendingCardIds { get; } = new();
        public List<string> Warnings { get; } = new();
        public List<string> Errors { get; } = new();
        public bool Saved { get; set; }
        public bool NoChanges => CreatedPacks.Count == 0 &&
            NewCardIds.Count == 0 && RemovedPendingCardIds.Count == 0 &&
            string.Equals(PreviousHash, SourceHash, StringComparison.Ordinal);
    }
}
